version: '2.3'
services:

  # Schema Registry application gets installed under /opt/hortonworks-registry-`version` directory
  # If we assign a "Container name" to registry, then it might clash with other registry server while scaling the registry application.
  # Let it take auto assigned unique container name.
  registry:
    build:
      context: "images/registry"
      dockerfile: "Dockerfile"
      args:
        - "REGISTRY_VERSION=0.5.0"
    image: schema-registry
    ports:
      - "9010-9020:9090"
      - "9030-9040:9091"
    depends_on: # TODO add health check for oracle db
      oracle-dev:
        condition: service_started
      kafka:
        condition: service_started
    links:
      - oracle-dev
    environment:
      DB_TYPE: oracle
      DATA_SRC_CLASS_NAME: oracle.jdbc.pool.OracleDataSource
      DB_URL: jdbc:oracle:thin:@oracle-dev:1521:xe
      DB_USER: registry_user
      DB_PASSWORD: password

  # Oracle gets installed under /u01/app/oracle/product/12.1.0/xe directory
  # Oracle data are stored under /u01/app/oracle
  oracle-dev:
    build:
      context: "images/registry"
      dockerfile: "OracleDockerfile"
    image: oracle-12c
    environment:
      DBCA_TOTAL_MEMORY: 1024
    ports:
      - "1521:1521"
      - "8080:8080"
    container_name: oracle

  # Zookeeper gets installed under /opt/zookeeper directory
  # Data & log are stored under /data and /datalog directories
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"

  # Kafka gets installed under /opt/kafka directory
  # Data are stored under /kafka directory
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "1099:1099"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "log_test0:1:1"
      KAFKA_BROKER_ID: 0
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false
                       -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1
                       -Dcom.sun.management.jmxremote.rmi.port=1099"
      JMX_PORT: 1099
    depends_on:
      zookeeper:
        condition: service_started
    links:
      - zookeeper

  # Download the ojdbc jar manually, and add it in extlibs - http://www.oracle.com/technetwork/database/features/jdbc/default-2280470.html