version: '2.3'
services:

  # Schema Registry application gets installed under /opt/hortonworks-registry-`version` directory
  registry:
    build:
      context: "images/registry"
      dockerfile: "Dockerfile"
      args:
        - "REGISTRY_VERSION=0.5.0"
    image: schema-registry
    ports:
      - "9010-9020:9090"
      - "9030-9040:9091"
    depends_on:
      oracle-dev:
        condition: service_healthy
      kafka:
        condition: service_started
    links:
      - oracle-dev
    environment:
      DB_TYPE: oracle
      DATA_SRC_CLASS_NAME: oracle.jdbc.pool.OracleDataSource
      DB_URL: jdbc:oracle:thin:@oracle-dev:1521:xe
      DB_USER: registry_user
      DB_PASSWORD: password
    volumes:
      - "./logs:/opt/registrylogs:rw"

  # Oracle gets installed under /u01/app/oracle/product/12.1.0/xe directory
  oracle-dev:
    image: sath89/oracle-12c
    volumes:
      - "./orclcustomscripts:/u01/app/oracle/scripts/startup:rw"
      - "./oracle-data:/u01/app/oracle:rw"
    environment:
      DBCA_TOTAL_MEMORY: 1024
    ports:
      - "1521:1521"
      - "8080:8080"

  # Zookeeper gets installed under /opt/zookeeper directory
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "./zk-data:/data:rw"
      - "./zk-datalog:/datalog:rw"

  # Kafka gets installed under /opt/kafka directory
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "1099:1099"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "log_test0:1:1"
      KAFKA_BROKER_ID: 0
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false
                       -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1
                       -Dcom.sun.management.jmxremote.rmi.port=1099"
      JMX_PORT: 1099
    depends_on:
      zookeeper:
        condition: service_started
    links:
      - zookeeper
    volumes:
      - "./kafka-data:/kafka:rw"

  #Connect database with following setting:
  #
  #hostname: localhost
  #port: 1521
  #sid: xe
  #service name: xe
  #username: system
  #password: oracle
  #To connect using sqlplus:
  #
  #<pre> sqlplus system/oracle@//localhost:1521/xe </pre>
  #
  #Password for SYS & SYSTEM:
  #
  #oracle

  # Download this jar manually, and add it in SR and bootstrap classpath - http://www.oracle.com/technetwork/database/features/jdbc/default-2280470.html


#  USER=sys
#  PASS=oracle
#  HOST=oracle-database
#  PORT=1521
#  SID=XE
#  HTTP_PORT=8080